### ISSUE TITLE
example-basic, breaks at: core = WebCore::Initialize(config);

### ISSUE THREAD

**Issue by rwebber** [razvanilin/ofxAwesomiumPlus#3]
with the latest Awesomium sdk installed, and OF 0.9.3
I can not get example-basic to run (all linking is good, checked 3 times)
Trying to build debug it breaks at ofxAwesomiumPlus.cpp line 372
core = WebCore::Initialize(config);

build for Release gives: Lnk2001 errors  ( swear all linking vars are setup correctly )

sorry of this isn't the right place for this.

**Comment by razvanilin** [comment]
I don't think I tried it with the latest OF so it might break. I will check
it as soon as I can, but I'm currently on holiday so it might take a bit of
time.

**Comment by rwebber** [comment]
greatly appreciated. I'm pretty new with OF

**Comment by rwebber** [comment]
wanted to let you know, that the issue seemed to be some corrupt file from the SDK.
After some messing about, replacing the required files in the build/bin seems to have fixed the issue.
I have this running nicely in OF 0.9.3 on windows.

I would like to know what your plans for ofxAwesomiumPlus::getState() is?
I could really use something here, and may be able to help out.
For now I am using IsLoading() but it doesn't fully serve my purpose.
Combining IsDocumentReady() and IsLoading() plus some others into a State is what I am imagining..
Let me know your thoughts and I can play with it.

**Comment by razvanilin** [comment]
Glad to hear that you managed to get it working.

My thoughts for getState() is to remove it completely and replace it with
another method described in the other opened issue #2 . So that state doesn't
actually describe the state (ready, loaded) of the page.

You can, for example, listen for the state of the DOM in javascript and
when the page is fully loaded, set the state to "LOADED" or something and
then listen for that in the OF app.

**Comment by rwebber** [comment]
I didn't see the other issue posted.
I saw the Domready function in the Awesomium Api, seems very useful.

SO, I spoke too soon.
I can build in debug, but release is giving me the following error:

Severity    Code    Description Project File    Line    Suppression State
Error   LNK2001 unresolved external symbol "__declspec(dllimport) public: __thiscall Awesomium::WebString::~WebString(void)" (__imp_??1WebString@Awesomium@@QAE@XZ) webviewUtility  C:\OF\of_v0.9.3_vs_release\apps\myApps\webviewUtility\main.obj  1   

After this there are many more LNK2001 unresolved external symbol errors, in the ofxAwesomeiumPlus.odj
Seems that something is not being linked in release.
Any insight into this would be greatly appreciated.

note: I also found that I need to #include "ofxAwesomiumPlus.h" after most other headers. Otherwise a DWORD error is given and the build fails (in debug). Perhaps something for the readme.

**Comment by rwebber** [comment]
Again, I'm being such a OF noob. Sorry..
I messed up the linking, in that I didn't get it done for both release and debug (missed that entirely... that won't happen again ;)
I really appreciate this addon... thanks for the great work.

**Comment by razvanilin** [comment]
Haha, don't worry I fell for that too one time :)

Thanks for pointing the DWORD error to me, I will give it a go soon and make sure I will include it in the readme. I am back home now and I might have a bit of free time to improve the addon a bit.

**Comment by rwebber** [comment]
Simplest method to repeatably cause the DWORD error, is to add:
#include "ofxOsc.h"
after including ofxAwesomiumPlus.h

Other plugins will cause this issue, but this is the one I confirmed the fix for. (load ofxOsc.h first)
additionally, you might (I have made this change, haven't confirmed its 100% necessary) need to declare the ofxAwesomiumPlus object before the other public stuff.
