### ISSUE TITLE
cannot compile on osx, of9.2, xcode7.3

### ISSUE THREAD

**Issue by samubence** [razvanilin/ofxAwesomiumPlus#4]
Hi, this works for me on windows like a charm, but I cannot compile on osx (probably the lack of my knowledge)
The platform specific description says:
Under the Architectures property, make sure 32-bit Universal is selected. 1. Under the Valid Architectures property, remove all architectures except i386.
without doing this I get errors like this:
Undefined symbols for architecture x86_64:
  "Awesomium::JSArray::operator[](unsigned int) const", referenced from:
      ofxAwesomiumPlus::OnChangeState(Awesomium::WebView*, Awesomium::JSArray const&) in ofxAwesomiumPlus.o

by trying to compile with the recommended settings errors get even worse. (there is not even a " 32-bit Universal" in the dropdown...)
any help would be much appreciated.

**Comment by razvanilin** [comment]
Hi there,
I use the same version of XCode but I have all the settings mentioned in the guide. It's weird that these don't show up for you.
Just to make sure, have you clicked the project name in the project explorer and then did you click on the `Build Settings`? Under `Architecure` set up `Universal (32/64 bit) ...`. Then `Valid Architectures` se to `x86_64` and `i386`.

Let me know how it goes.

**Comment by razvanilin** [comment]
I'll close the issue because this is an Awesomium/IDE related problem
