### ISSUE TITLE
can this run on the raspberry pi 

### ISSUE THREAD

**Issue by JeanPierreFig** [razvanilin/ofxAwesomiumPlus#5]
This is not really an issue but can it run on a raspberry pi and can it run fullscreen with out window frame. :)

**Comment by razvanilin** [comment]
awesomium can be [set up for Linux](http://wiki.awesomium.com/getting-started/setting-up-on-linux.html) so I would guess that everything should work properly.

**Comment by JeanPierreFig** [comment]
ok thanks will test and will report back.

**Comment by razvanilin** [comment]
Cool! Keep in mind that Awesomium is running a Chromium-like engine which might be a bit heavy on the Pi
